### ISSUE TITLE
 pip install -e napari-large-3d-vis 

### ISSUE THREAD

**Issue by thjimmylee** [StasMakarchuk/napari-large-3d-vis#1]
Hi, I run into the issue below when trying to install:

```
$ pip install -e napari-large-3d-vis 
Obtaining file:///Users/tl7/Downloads/napari-large-3d-vis
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: napari==0.4.18 in /Users/tl7/micromamba/envs/napari/lib/python3.9/site-packages (from napari-large-3D-vis-ch==0.0.1) (0.4.18)
Collecting numpy==1.24.4 (from napari-large-3D-vis-ch==0.0.1)
  Downloading numpy-1.24.4-cp39-cp39-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting magicgui==0.8.0 (from napari-large-3D-vis-ch==0.0.1)
  Downloading magicgui-0.8.0-py3-none-any.whl.metadata (8.3 kB)
Collecting tifffile==2023.7.10 (from napari-large-3D-vis-ch==0.0.1)
  Downloading tifffile-2023.7.10-py3-none-any.whl.metadata (31 kB)
Collecting zarr==2.10.0 (from napari-large-3D-vis-ch==0.0.1)
  Downloading zarr-2.10.0-py3-none-any.whl (146 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.0/146.0 kB 8.6 MB/s eta 0:00:00
Collecting dask==2023.5.0 (from napari-large-3D-vis-ch==0.0.1)
  Downloading dask-2023.5.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: vispy==0.12.2 in /Users/tl7/micromamba/envs/napari/lib/python3.9/site-packages (from napari-large-3D-vis-ch==0.0.1) (0.12.2)
Collecting PyYAML==5.4.1 (from napari-large-3D-vis-ch==0.0.1)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 7.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/tl7/micromamba/envs/napari/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/tl7/micromamba/envs/napari/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/tl7/micromamba/envs/napari/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/qt/wlfwvjyn6zn84sfygh5548qm0000gq/T/pip-build-env-ipzw2feq/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by thjimmylee** [comment]
The new update works! Thank you very much for fixing !
